aws_access_key = "AKIAJABIMKYCP5RPAGPA"
aws_secret_key = "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"
aws_key_path = "~/.ssh/"
aws_key_name = "aws.test"
instance_type = "t2.micro"
docker_image = "nginx:latest"