region = "us-west-1"
aws_access_key = "AKIAJABIMKYCP5RPAGPA"
aws_secret_key = "KTR2jzXYIF424mb/Tr/Fb0FVsKORzLMnDmYHvUob"
aws_key_path = "~/.ssh/"
aws_key_name = "aws.test"
app_name = "example-express"